- hosts: nodes
  become: yes
  tags:
    - never
    - docker
  roles:
    - common
    - docker/install
    - docker/deploy

- hosts: nodes
  become: yes
  tags:
    - never
    - microk8s
  roles:
    - common
    - microk8s/install
    - microk8s/deploy
