- name: Add apt signing key for Docker
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add apt repository for Docker
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable
    state: present
    filename: docker

- name: Install Docker and its dependencies
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: present
    update_cache: yes

- name: Ensure Docker is running
  service:
    name: docker
    state: started

- name: Retrive OS name
  shell: uname -s
  register: os_name

- name: Retrive system architecture
  shell: uname -m
  register: sys_arch

- name: Download and install Docker Compose
  get_url:
    url: "https://github.com/docker/compose/releases/download/1.29.1/docker-compose-{{ os_name }}-{{ sys_arch }}"
    dest: /usr/local/bin/docker-compose
    mode: "0774"

- name: Create Docker Compose symlink
  file:
    src: /usr/local/bin/docker-compose
    dest: /usr/bin/docker-compose
    state: link
