nextcloud:
  host: "{{ nextcloud_host }}"
  username: "{{ nextcloud_user }}"
  password: "{{ nextcloud_password }}"
  configs:
    custom.config.php: |-
      <?php
      $CONFIG = array (
        'overwriteprotocol' => 'https',
        'overwrite.cli.url' => 'https://{{ nextcloud_host }}',
        'filelocking.enabled' => 'true',
        'loglevel' => '2',
        'enable_previews' => false
      );

ingress:
  enabled: true
  tls:
    - hosts:
        - "{{ nextcloud_host }}"
      secretName: nextcloud-tls
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: 4G
    kubernetes.io/tls-acme: "true"
    cert-manager.io/cluster-issuer: letsencrypt-production
    acme.cert-manager.io/http01-edit-in-place: "true"
    nginx.ingress.kubernetes.io/server-snippet: |-
      server_tokens off;
      proxy_hide_header X-Powered-By;
      rewrite ^/.well-known/webfinger /public.php?service=webfinger last;
      rewrite ^/.well-known/host-meta /public.php?service=host-meta last;
      rewrite ^/.well-known/host-meta.json /public.php?service=host-meta-json;
      location = /.well-known/carddav {
        return 301 $scheme://$host/remote.php/dav;
      }
      location = /.well-known/caldav {
        return 301 $scheme://$host/remote.php/dav;
      }
      location = /robots.txt {
        allow all;
        log_not_found off;
        access_log off;
      }
      location ~ ^/(?:build|tests|config|lib|3rdparty|templates|data)/ {
        deny all;
      }
      location ~ ^/(?:autotest|occ|issue|indie|db_|console) {
        deny all;
      }

persistence:
  enabled: true
  size: 100Gi

internalDatabase:
  enabled: false
mariadb:
  enabled: false

externalDatabase:
  enabled: true
  type: mysql
  host: mariadb
  user: nextcloud
  password: nextcloud
  database: nextcloud
